### ISSUE TITLE
Application doesn't seem launch (?)

### ISSUE THREAD

**Issue by cadavren** [Zoobumafu/BeatSaber-Playlist-Master#1]
Hello!
I tried to run the application (both setup.exe and BeatSaberPlaylistMaster) but I don't actually undertsand why it doesn't launch anything.

I do have PlaylistManager.dll installed (before trying to install BeatSaber-Playslit-Master) and I also have the BeatSaberPlaylistMaster.dll installed, both are in the plugin registry.

Actually I don't really understand how it works. Am I supposed to open the game at least once before trying to use the application ?

Here are what I get for each different ways I tried to open it (sorry it is french so you may need to use a translator, if needed I can translate a little bit of it but it would take too long for me to translate everything) :

1rst try, from here (setup as been unzipped and launched once) : 
![image](https://user-images.githubusercontent.com/61839268/113148146-cd478000-9231-11eb-90e7-f6c538d5fd7d.png)

>!INFORMATIONS SUR LA VERSION DE LA PLATEFORME
	Windows 			: 10.0.19042.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.4270.0 built by: NET48REL1LAST_C
	clr.dll 			: 4.8.4341.0 built by: NET48REL1LAST_C
	dfdll.dll 			: 4.8.4270.0 built by: NET48REL1LAST_C
	dfshim.dll 			: 10.0.19041.1 (WinBuild.160101.0800)

>!SOURCES
	Url de déploiement			 : file:///E:/Download/BeatSaberPlaylistMaster/Application%20Files/BeatSaberPlaylistMaster_1_0_0_1/BeatSaberPlaylistMaster.application

>!IDENTITÉS
	Identité de déploiement		 : BeatSaberPlaylistMaster.application, Version=1.0.0.1, Culture=neutral, PublicKeyToken=e31a0ca7f72714fa, processorArchitecture=msil

>!RÉSUMÉ DES APPLICATIONS
	* Application installable.

>!RÉSUMÉ DES ERREURS
	Un résumé des erreurs est fourni ci-dessous. Les détails de ces erreurs sont indiqués plus loin dans le fichier journal.
	* L'activation de E:\Download\BeatSaberPlaylistMaster\Application Files\BeatSaberPlaylistMaster_1_0_0_1\BeatSaberPlaylistMaster.application a provoqué une exception. Les messages d'erreur suivants ont été détectés :
		+ Impossible de démarrer l'application BeatSaberPlaylistMaster à partir de cet emplacement car elle est déjà installée dans un autre emplacement.
		+ Impossible de démarrer l'application BeatSaberPlaylistMaster à partir de l'emplacement file:///E:/Download/BeatSaberPlaylistMaster/Application%20Files/BeatSaberPlaylistMaster_1_0_0_1/BeatSaberPlaylistMaster.application car elle est déjà installée dans l'emplacement file:///E:/Download/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application. Vous pouvez la démarrer à partir de l'emplacement file:///E:/Download/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application ou la désinstaller puis la réinstaller dans l'emplacement file:///E:/Download/BeatSaberPlaylistMaster/Application%20Files/BeatSaberPlaylistMaster_1_0_0_1/BeatSaberPlaylistMaster.application. Si vous réinstallez l'application, les personnalisations apportées à cette application risquent d'être perdues.

>!RÉSUMÉ DES ERREURS DE LA TRANSACTION DU MAGASIN DE COMPOSANTS
	Aucune erreur de transaction n'a été détectée.

>!AVERTISSEMENTS
	Aucun avertissement n'a été émis pendant cette opération.

>!ÉTAT DE LA PROGRESSION DE L'OPÉRATION
	* [31/03/2021 14:55:19] : L'activation de E:\Download\BeatSaberPlaylistMaster\Application Files\BeatSaberPlaylistMaster_1_0_0_1\BeatSaberPlaylistMaster.application a commencé.
	* [31/03/2021 14:55:19] : Traitement du manifeste de déploiement terminé.

>!DÉTAILS DE L'ERREUR
	Les erreurs suivantes ont été détectées au cours de cette opération.
	* [31/03/2021 14:55:19] System.Deployment.Application.DeploymentException (DeploymentUriDifferent)
		- Impossible de démarrer l'application BeatSaberPlaylistMaster à partir de cet emplacement car elle est déjà installée dans un autre emplacement.
		- Source : System.Deployment
		- Trace de la pile :
			à System.Deployment.Application.ApplicationActivator.CheckDeploymentProviderValidity(ActivationDescription actDesc, SubscriptionState subState)
			à System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			à System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
			à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			à System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			à System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Exception interne ---
		System.Deployment.Application.DeploymentException (DeploymentUriDifferent)
		- Impossible de démarrer l'application BeatSaberPlaylistMaster à partir de l'emplacement file:///E:/Download/BeatSaberPlaylistMaster/Application%20Files/BeatSaberPlaylistMaster_1_0_0_1/BeatSaberPlaylistMaster.application car elle est déjà installée dans l'emplacement file:///E:/Download/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application. Vous pouvez la démarrer à partir de l'emplacement file:///E:/Download/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application ou la désinstaller puis la réinstaller dans l'emplacement file:///E:/Download/BeatSaberPlaylistMaster/Application%20Files/BeatSaberPlaylistMaster_1_0_0_1/BeatSaberPlaylistMaster.application. Si vous réinstallez l'application, les personnalisations apportées à cette application risquent d'être perdues.
		- Source : 
		- Trace de la pile :

>!DÉTAILS DE LA TRANSACTION DU MAGASIN DE COMPOSANTS
	Aucune information disponible sur la transaction.

2nd try, from here : 
![image](https://user-images.githubusercontent.com/61839268/113148400-1566a280-9232-11eb-86cb-ba1601cf29eb.png)

I only get the image below less than a second and nothing else will show up after that.

![image](https://user-images.githubusercontent.com/61839268/113148364-0c75d100-9232-11eb-9e0a-f9b7ad012187.png)

Then, I tried to install it directly on my beatsaber folder (I guess I should've done that first ?), but I get this errors :

From the setup :

![image](https://user-images.githubusercontent.com/61839268/113148668-68d8f080-9232-11eb-9a98-393599a5444d.png)
(can't install)

The details :
>!INFORMATIONS SUR LA VERSION DE LA PLATEFORME
	Windows 			: 10.0.19042.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.4270.0 built by: NET48REL1LAST_C
	clr.dll 			: 4.8.4341.0 built by: NET48REL1LAST_C
	dfdll.dll 			: 4.8.4270.0 built by: NET48REL1LAST_C
	dfshim.dll 			: 10.0.19041.1 (WinBuild.160101.0800)

>!SOURCES
	Url de déploiement			 : file:///E:/Program%20Files%20(x86)/Steam/steamapps/common/Beat%20Saber/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application

>!IDENTITÉS
	Identité de déploiement		 : BeatSaberPlaylistMaster.application, Version=1.0.0.1, Culture=neutral, PublicKeyToken=e31a0ca7f72714fa, processorArchitecture=msil

>!RÉSUMÉ DES APPLICATIONS
	* Application installable.

>!RÉSUMÉ DES ERREURS
	Un résumé des erreurs est fourni ci-dessous. Les détails de ces erreurs sont indiqués plus loin dans le fichier journal.
	* L'activation de E:\Program Files (x86)\Steam\steamapps\common\Beat Saber\BeatSaberPlaylistMaster\BeatSaberPlaylistMaster.application a provoqué une exception. Les messages d'erreur suivants ont été détectés :
		+ Impossible de démarrer l'application BeatSaberPlaylistMaster à partir de cet emplacement car elle est déjà installée dans un autre emplacement.
		+ Impossible de démarrer l'application BeatSaberPlaylistMaster à partir de l'emplacement file:///E:/Program%20Files%20(x86)/Steam/steamapps/common/Beat%20Saber/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application car elle est déjà installée dans l'emplacement file:///E:/Download/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application. Vous pouvez la démarrer à partir de l'emplacement file:///E:/Download/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application ou la désinstaller puis la réinstaller dans l'emplacement file:///E:/Program%20Files%20(x86)/Steam/steamapps/common/Beat%20Saber/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application. Si vous réinstallez l'application, les personnalisations apportées à cette application risquent d'être perdues.

>!RÉSUMÉ DES ERREURS DE LA TRANSACTION DU MAGASIN DE COMPOSANTS
	Aucune erreur de transaction n'a été détectée.

>!AVERTISSEMENTS
	Aucun avertissement n'a été émis pendant cette opération.

>!ÉTAT DE LA PROGRESSION DE L'OPÉRATION
	* [31/03/2021 15:04:23] : L'activation de E:\Program Files (x86)\Steam\steamapps\common\Beat Saber\BeatSaberPlaylistMaster\BeatSaberPlaylistMaster.application a commencé.
	* [31/03/2021 15:04:23] : Traitement du manifeste de déploiement terminé.

>!DÉTAILS DE L'ERREUR
	Les erreurs suivantes ont été détectées au cours de cette opération.
	* [31/03/2021 15:04:23] System.Deployment.Application.DeploymentException (DeploymentUriDifferent)
		- Impossible de démarrer l'application BeatSaberPlaylistMaster à partir de cet emplacement car elle est déjà installée dans un autre emplacement.
		- Source : System.Deployment
		- Trace de la pile :
			à System.Deployment.Application.ApplicationActivator.CheckDeploymentProviderValidity(ActivationDescription actDesc, SubscriptionState subState)
			à System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			à System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
			à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			à System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			à System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Exception interne ---
		System.Deployment.Application.DeploymentException (DeploymentUriDifferent)
		- Impossible de démarrer l'application BeatSaberPlaylistMaster à partir de l'emplacement file:///E:/Program%20Files%20(x86)/Steam/steamapps/common/Beat%20Saber/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application car elle est déjà installée dans l'emplacement file:///E:/Download/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application. Vous pouvez la démarrer à partir de l'emplacement file:///E:/Download/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application ou la désinstaller puis la réinstaller dans l'emplacement file:///E:/Program%20Files%20(x86)/Steam/steamapps/common/Beat%20Saber/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application. Si vous réinstallez l'application, les personnalisations apportées à cette application risquent d'être perdues.
		- Source : 
		- Trace de la pile :

>!DÉTAILS DE LA TRANSACTION DU MAGASIN DE COMPOSANTS
	Aucune information disponible sur la transaction.

From the Application :

(same message, can't install)

The details: 
>!INFORMATIONS SUR LA VERSION DE LA PLATEFORME
	Windows 			: 10.0.19042.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.4270.0 built by: NET48REL1LAST_C
	clr.dll 			: 4.8.4341.0 built by: NET48REL1LAST_C
	dfdll.dll 			: 4.8.4270.0 built by: NET48REL1LAST_C
	dfshim.dll 			: 10.0.19041.1 (WinBuild.160101.0800)

>!SOURCES
	Url de déploiement			 : file:///E:/Program%20Files%20(x86)/Steam/steamapps/common/Beat%20Saber/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application

>!IDENTITÉS
	Identité de déploiement		 : BeatSaberPlaylistMaster.application, Version=1.0.0.1, Culture=neutral, PublicKeyToken=e31a0ca7f72714fa, processorArchitecture=msil

>!RÉSUMÉ DES APPLICATIONS
	* Application installable.

>!RÉSUMÉ DES ERREURS
	Un résumé des erreurs est fourni ci-dessous. Les détails de ces erreurs sont indiqués plus loin dans le fichier journal.
	* L'activation de E:\Program Files (x86)\Steam\steamapps\common\Beat Saber\BeatSaberPlaylistMaster\BeatSaberPlaylistMaster.application a provoqué une exception. Les messages d'erreur suivants ont été détectés :
		+ Impossible de démarrer l'application BeatSaberPlaylistMaster à partir de cet emplacement car elle est déjà installée dans un autre emplacement.
		+ Impossible de démarrer l'application BeatSaberPlaylistMaster à partir de l'emplacement file:///E:/Program%20Files%20(x86)/Steam/steamapps/common/Beat%20Saber/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application car elle est déjà installée dans l'emplacement file:///E:/Download/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application. Vous pouvez la démarrer à partir de l'emplacement file:///E:/Download/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application ou la désinstaller puis la réinstaller dans l'emplacement file:///E:/Program%20Files%20(x86)/Steam/steamapps/common/Beat%20Saber/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application. Si vous réinstallez l'application, les personnalisations apportées à cette application risquent d'être perdues.

>!RÉSUMÉ DES ERREURS DE LA TRANSACTION DU MAGASIN DE COMPOSANTS
	Aucune erreur de transaction n'a été détectée.

>!AVERTISSEMENTS
	Aucun avertissement n'a été émis pendant cette opération.

>!ÉTAT DE LA PROGRESSION DE L'OPÉRATION
	* [31/03/2021 15:04:23] : L'activation de E:\Program Files (x86)\Steam\steamapps\common\Beat Saber\BeatSaberPlaylistMaster\BeatSaberPlaylistMaster.application a commencé.
	* [31/03/2021 15:04:23] : Traitement du manifeste de déploiement terminé.

>!DÉTAILS DE L'ERREUR
	Les erreurs suivantes ont été détectées au cours de cette opération.
	* [31/03/2021 15:04:23] System.Deployment.Application.DeploymentException (DeploymentUriDifferent)
		- Impossible de démarrer l'application BeatSaberPlaylistMaster à partir de cet emplacement car elle est déjà installée dans un autre emplacement.
		- Source : System.Deployment
		- Trace de la pile :
			à System.Deployment.Application.ApplicationActivator.CheckDeploymentProviderValidity(ActivationDescription actDesc, SubscriptionState subState)
			à System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			à System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
			à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			à System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			à System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Exception interne ---
		System.Deployment.Application.DeploymentException (DeploymentUriDifferent)
		- Impossible de démarrer l'application BeatSaberPlaylistMaster à partir de l'emplacement file:///E:/Program%20Files%20(x86)/Steam/steamapps/common/Beat%20Saber/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application car elle est déjà installée dans l'emplacement file:///E:/Download/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application. Vous pouvez la démarrer à partir de l'emplacement file:///E:/Download/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application ou la désinstaller puis la réinstaller dans l'emplacement file:///E:/Program%20Files%20(x86)/Steam/steamapps/common/Beat%20Saber/BeatSaberPlaylistMaster/BeatSaberPlaylistMaster.application. Si vous réinstallez l'application, les personnalisations apportées à cette application risquent d'être perdues.
		- Source : 
		- Trace de la pile :

>!DÉTAILS DE LA TRANSACTION DU MAGASIN DE COMPOSANTS
	Aucune information disponible sur la transaction.

Is there a unistallator ? I can't see a way to uninstalling it for now

Hope it isn't too bothering

Have a nice day or night !

**Comment by Zoobumafu** [comment]
Hey there, 
Thank you for this detailed log,
I have seen this problem with multiple users, I believe it has something to do with the windows forms, I am searching for another way to compile the software so it can install like traditional software.

There is no uninstaller as file, but the control panel - programs and features, does keep a registry of the software, you can uninstall it from there.

**Comment by cadavren** [comment]
EDIT 05/04/2021 : This morning I woke up to my computer saying BeatSaberPlaylistMaster is a menace so I guess that plays ith the fact it doesn't launch on my side ? Maybe

![image](https://user-images.githubusercontent.com/61839268/113997835-ce436780-9858-11eb-866f-437bdccdc84a.png)


Hi again, thank you for your awnser !

I tried again with the new NoInstall zip you provided but it doesn't look like it changes anything for me : the app still doesn't launch for some reason.
I don't have any error, nor feedback telling me why or what it's* doing so I really can't tell anything else about the issue, I wish I could.
I did unzip the folder "release", and tried to open either the one in app.publish and the one in the release folder.

The app is also not repertoried in the programs and features anymore.

Do I have to put the release folder somewhere specifically?

Also a side note : when I'm trying to install the app with the installer provided in the new NoInstall Release, I get this
![image](https://user-images.githubusercontent.com/61839268/113766508-cb902780-971d-11eb-95a1-abdfc93bb4be.png)
The app can't be downloaded, files are missing* (I guess it's wanted, but I'm not sure so I rather let you know)

Log Details :
>! INFORMATIONS SUR LA VERSION DE LA PLATEFORME
	Windows 			: 10.0.19042.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.4270.0 built by: NET48REL1LAST_C
	clr.dll 			: 4.8.4341.0 built by: NET48REL1LAST_C
	dfdll.dll 			: 4.8.4270.0 built by: NET48REL1LAST_C
	dfshim.dll 			: 10.0.19041.1 (WinBuild.160101.0800)

>!SOURCES
	Url de déploiement			 : file:///E:/Program%20Files%20(x86)/Steam/steamapps/common/Beat%20Saber/Release/BeatSaberPlaylistMaster.application
	Url de l'application			 : file:///E:/Program%20Files%20(x86)/Steam/steamapps/common/Beat%20Saber/Release/BeatSaberPlaylistMaster.exe.manifest

>!IDENTITÉS
	Identité de déploiement		 : BeatSaberPlaylistMaster.application, Version=1.0.0.2, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=msil
	Identité de l'application		 : BeatSaberPlaylistMaster.exe, Version=1.0.0.2, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=msil, type=win32

>!RÉSUMÉ DES APPLICATIONS
	* Application installable.

>!RÉSUMÉ DES ERREURS
	Un résumé des erreurs est fourni ci-dessous. Les détails de ces erreurs sont indiqués plus loin dans le fichier journal.
	* L'activation de E:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Release\BeatSaberPlaylistMaster.application a provoqué une exception. Les messages d'erreur suivants ont été détectés :
		+ Échec du téléchargement de file:///E:/Program Files (x86)/Steam/steamapps/common/Beat Saber/Release/computer-icons-playlist-download-png-favpng-bJ8Ya6wH8z9W1srerrT4wwhrr.ico.deploy.
		+ Le fichier 'E:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Release\computer-icons-playlist-download-png-favpng-bJ8Ya6wH8z9W1srerrT4wwhrr.ico.deploy' est introuvable.
		+ Le fichier 'E:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Release\computer-icons-playlist-download-png-favpng-bJ8Ya6wH8z9W1srerrT4wwhrr.ico.deploy' est introuvable.
		+ Le fichier 'E:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Release\computer-icons-playlist-download-png-favpng-bJ8Ya6wH8z9W1srerrT4wwhrr.ico.deploy' est introuvable.

>!RÉSUMÉ DES ERREURS DE LA TRANSACTION DU MAGASIN DE COMPOSANTS
	Aucune erreur de transaction n'a été détectée.

>!AVERTISSEMENTS
	* Le manifeste pour cette application ne comporte pas de signature. La validation de signature sera ignorée.
	* Le manifeste pour cette application ne comporte pas de signature. La validation de signature sera ignorée.

>!ÉTAT DE LA PROGRESSION DE L'OPÉRATION
	* [06/04/2021 21:18:19] : L'activation de E:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Release\BeatSaberPlaylistMaster.application a commencé.
	* [06/04/2021 21:18:19] : Traitement du manifeste de déploiement terminé.
	* [06/04/2021 21:18:19] : L'installation de l'application a commencé.
	* [06/04/2021 21:18:19] : Traitement du manifeste de l'application terminé.
	* [06/04/2021 21:18:22] : Une version 4.0.30319 du runtime compatible a été trouvée.
	* [06/04/2021 21:18:22] : Requête de confiance et détection de plateforme terminée.

>!DÉTAILS DE L'ERREUR
	Les erreurs suivantes ont été détectées au cours de cette opération.
	* [06/04/2021 21:18:22] System.Deployment.Application.DeploymentDownloadException (sous-type inconnu)
		- Échec du téléchargement de file:///E:/Program Files (x86)/Steam/steamapps/common/Beat Saber/Release/computer-icons-playlist-download-png-favpng-bJ8Ya6wH8z9W1srerrT4wwhrr.ico.deploy.
		- Source : System.Deployment
		- Trace de la pile :
			à System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			à System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			à System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			à System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			à System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			à System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			à System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			à System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
			à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			à System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			à System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Exception interne ---
		System.Net.WebException
		- Le fichier 'E:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Release\computer-icons-playlist-download-png-favpng-bJ8Ya6wH8z9W1srerrT4wwhrr.ico.deploy' est introuvable.
		- Source : System
		- Trace de la pile :
			à System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
			à System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
		--- Exception interne ---
		System.Net.WebException
		- Le fichier 'E:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Release\computer-icons-playlist-download-png-favpng-bJ8Ya6wH8z9W1srerrT4wwhrr.ico.deploy' est introuvable.
		- Source : System
		- Trace de la pile :
			à System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
			à System.Net.FileWebRequest.GetResponseCallback(Object state)
		--- Exception interne ---
		System.IO.FileNotFoundException
		- Le fichier 'E:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Release\computer-icons-playlist-download-png-favpng-bJ8Ya6wH8z9W1srerrT4wwhrr.ico.deploy' est introuvable.
		- Source : mscorlib
		- Trace de la pile :
			à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
			à System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
			à System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
			à System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
			à System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)

>!DÉTAILS DE LA TRANSACTION DU MAGASIN DE COMPOSANTS
	Aucune information disponible sur la transaction.


Before sending you this message*, I also tried

To reinstall the software with the original "setup" app. Then put the release folder into the BeatSaberPlaylistMaster folder, and launch the app from the "release" folder. Didn't work
Tried to launch the app as administrator. Didn't work. 
I'm still trying things as I send this message, if I ever find a way that works (or others that don't) I'll edit this message.

I hope this is not too confusing. Please tell me if you need me to clarify a point !

Have a nice day or night.

**Comment by Zoobumafu** [comment]
Hi @cadavren , 
I haven't found the reason as to why the software appears as virus on some users' end, I suspect it has to do with the program using the registry to detect the BeatSaber's installation directory.

I have recompiled code and made a competent setup.exe file this update, I believe there is a good chance it will work for you now.
see [Releases](https://github.com/Zoobumafu/BeatSaber-Playlist-Master/releases)

**Comment by cadavren** [comment]
Hi !

EDIT 10/04/2021 : I'm openning another issue and closing this one since it hasn't got anything to do with the launch or install now

Update on the situation : It launchs fine with the new setup installation !

Thank you a lot for your work !
